name: licenta_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  percent_indicator: ^3.4.0
  http: ^0.13.6
  flutter_neumorphic: ^3.2.0
  flutter_launcher_icons: ^0.9.1
  font_awesome_flutter: ^9.1.0
  awesome_notifications: ^0.0.6+10
  fl_chart: ^0.60.0
  carousel_slider: ^4.0.0-nullsafety.0
  cron: ^0.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appIcon.png"
  adaptive_icon_background: "assets/app_icon_background.png"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"


flutter:
  uses-material-design: true

  assets:
    - assets/